new_flap_eg={
  "category": "WARN",
  "eventId": "NETWORK-DEVICES-3-210",
  "domain": "Know Your Network",
  "description": None,
  "ciscoDnaEventLink": "dna/assurance/issueDetails?issueId=e24150f9-00b4-4164-aeb5-3abb74ddec00",
  "tags": None,
  "instanceId": "e24150f9-00b4-4164-aeb5-3abb74ddec00",
  "namespace": "ASSURANCE",
  "tntId": "",
  "name": None,
  "tenantId": "",
  "note": "",
  "source": "ndp",
  "version": None,
  "details": {
    "Assurance Issue Status": "active",
    "Assurance Issue Details": "Switch 3850-remote.adamlab.cisco.com Interface GigabitEthernet1/0/22 is flapping",
    "Assurance Issue Priority": "P3",
    "Device": "10.10.6.2",
    "Type": "Network Device",
    "Assurance Issue Category": "Device",
    "Assurance Issue Name": "Interface GigabitEthernet1/0/22 is Flapping on Network Device 10.10.6.2"
  },
  "context": None,
  "timestamp": 1565769512151,
  "subDomain": "Devices",
  "type": "NETWORK",
  "severity": 3
}